### PR TITLE
convert to a template for the manifest

### PR DESCRIPTION
**Pull request by KevinMarquette**
The manifest is now generated from a template. I slimmed it down and changed the default exports to `@()`. This also resolves an issue with a PSScriptAnalyser rule that would fail a new module.

I also removed the version prompt and just defaulted it to `0.1.0`

### CODE REVIEW

**Comment by ccrowhurstram** [comment]
`FunctionsToExport: '*'` is still a useful default as it means you don't have to check in changes to the Manifest file whenever a new public function is added.

Or am I missing something?

**Comment by KevinMarquette** [comment]
The reason why script analyzer was flagging that is because it's a best practice not to use the wildcard. By using a `*` for any one of those properties, PowerShell has to process the whole psm1 file to figure out what it exports. This is fine when you are importing the module, but starting with PS 5.0 they stopped trying to perform autoloading discovery for modules that use the `*`.

I felt it was better to default it to `@()` to encourage that best practice and allow the user to make a conscious decision to use the `*`

**Comment by christianacca** [comment]
But the deployed version of of the module will have an explicit list of functions, so the `*` is just during development so not a problem in my opinion.

**Comment by KevinMarquette** [comment]
That is a fair point that I didn't consider.

**Pull request merged**
